<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MailKit" Version="4.14.1" />
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="9.0.10" />
	  <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.10" />
	  <PackageReference Include="Microsoft.Extensions.Identity.Core" Version="9.0.10" />
	  <PackageReference Include="MimeKit" Version="4.14.0" />
	  <PackageReference Include="QRCoder" Version="1.7.0" />
	  <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />


  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BuildingBlock.Application\BuildingBlock.Application.csproj" />
  </ItemGroup>

</Project>
