// <auto-generated />
using System;
using CustomerSurvey.infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CustomerSurvey.infrastructure.Migrations
{
    [DbContext(typeof(PlatformWriteDbContext))]
    [Migration("20260519133010_AddAnoTemplate")]
    partial class AddAnoTemplate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.AnonymousSurveyAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnonymousSurveyResponseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnonymousTemplateQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuestionType")
                        .HasColumnType("int");

                    b.Property<Guid?>("SelectedQuestionOptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SmileValue")
                        .HasColumnType("int");

                    b.Property<int?>("StarRatingValue")
                        .HasColumnType("int");

                    b.Property<string>("TextAnswer")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("VoiceFileName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("AnonymousTemplateQuestionId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SelectedQuestionOptionId");

                    b.HasIndex("AnonymousSurveyResponseId", "AnonymousTemplateQuestionId")
                        .IsUnique();

                    b.ToTable("AnonymousSurveyAnswer");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.AnonymousSurveyResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActualScore")
                        .HasColumnType("int");

                    b.Property<Guid>("AnonymousTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxScore")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("ScorePercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("SubmittedOnUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AnonymousTemplateId");

                    b.HasIndex("SubmittedOnUtc");

                    b.HasIndex("AnonymousTemplateId", "SubmittedOnUtc");

                    b.ToTable("AnonymousSurveyResponse");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.AnonymousSurveyResponseCustomInputValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnonymousSurveyResponseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnonymousTemplateCustomInputId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IntegerValue")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StringValue")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<int>("TypeSnapshot")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnonymousSurveyResponseId");

                    b.HasIndex("AnonymousTemplateCustomInputId");

                    b.HasIndex("AnonymousSurveyResponseId", "AnonymousTemplateCustomInputId")
                        .IsUnique();

                    b.ToTable("AnonymousSurveyResponseCustomInputValue", null, t =>
                        {
                            t.HasCheckConstraint("CK_ASRCIV_Integer_Value", "([TypeSnapshot] <> 2) OR ([IntegerValue] IS NOT NULL AND [StringValue] IS NULL)");

                            t.HasCheckConstraint("CK_ASRCIV_String_Value", "([TypeSnapshot] <> 1) OR ([StringValue] IS NOT NULL AND [IntegerValue] IS NULL)");
                        });
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.AnonymousTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpireTo")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QrCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("AnonymousTemplate");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.AnonymousTemplateCustomInput", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnonymousTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("LabelAr")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LabelEn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("int");

                    b.Property<int?>("MaxValue")
                        .HasColumnType("int");

                    b.Property<int?>("MinLength")
                        .HasColumnType("int");

                    b.Property<int?>("MinValue")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnonymousTemplateId");

                    b.HasIndex("AnonymousTemplateId", "Name")
                        .IsUnique();

                    b.HasIndex("AnonymousTemplateId", "IsActive", "Order");

                    b.ToTable("AnonymousTemplateCustomInput", null, t =>
                        {
                            t.HasCheckConstraint("CK_AnonymousTemplateCustomInput_Integer_Validation", "([Type] <> 2) OR ([MinLength] IS NULL AND [MaxLength] IS NULL)");

                            t.HasCheckConstraint("CK_AnonymousTemplateCustomInput_Length_Range", "([MinLength] IS NULL OR [MaxLength] IS NULL OR [MaxLength] >= [MinLength])");

                            t.HasCheckConstraint("CK_AnonymousTemplateCustomInput_Order_Positive", "[Order] > 0");

                            t.HasCheckConstraint("CK_AnonymousTemplateCustomInput_String_Validation", "([Type] <> 1) OR ([MinValue] IS NULL AND [MaxValue] IS NULL)");

                            t.HasCheckConstraint("CK_AnonymousTemplateCustomInput_Value_Range", "([MinValue] IS NULL OR [MaxValue] IS NULL OR [MaxValue] >= [MinValue])");
                        });
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.AnonymousTemplateQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnonymousTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AnonymousTemplateId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("AnonymousTemplateId", "Order");

                    b.HasIndex("AnonymousTemplateId", "QuestionId")
                        .IsUnique();

                    b.ToTable("AnonymousTemplateQuestion", null, t =>
                        {
                            t.HasCheckConstraint("CK_AnonymousTemplateQuestion_Order_Positive", "[Order] > 0");
                        });
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.AnonymousTemplateQuestionCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AnonymousTemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChildAnonymousTemplateQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("ParentAnonymousTemplateQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SelectedQuestionOptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TriggerType")
                        .HasColumnType("int");

                    b.Property<int?>("TriggerValue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AnonymousTemplateId");

                    b.HasIndex("ChildAnonymousTemplateQuestionId");

                    b.HasIndex("ParentAnonymousTemplateQuestionId");

                    b.HasIndex("SelectedQuestionOptionId");

                    b.HasIndex("AnonymousTemplateId", "ParentAnonymousTemplateQuestionId", "ChildAnonymousTemplateQuestionId", "TriggerType", "SelectedQuestionOptionId", "TriggerValue")
                        .IsUnique()
                        .HasFilter("[SelectedQuestionOptionId] IS NOT NULL AND [TriggerValue] IS NOT NULL");

                    b.ToTable("AnonymousTemplateQuestionCondition", null, t =>
                        {
                            t.HasCheckConstraint("CK_AnonymousTemplateQuestionCondition_Not_Same_Question", "[ParentAnonymousTemplateQuestionId] <> [ChildAnonymousTemplateQuestionId]");

                            t.HasCheckConstraint("CK_AnonymousTemplateQuestionCondition_Order_Positive", "[Order] > 0");

                            t.HasCheckConstraint("CK_AnonymousTemplateQuestionCondition_RatingOrSmile", "([TriggerType] NOT IN (2, 3)) OR ([SelectedQuestionOptionId] IS NULL AND [TriggerValue] BETWEEN 1 AND 5)");

                            t.HasCheckConstraint("CK_AnonymousTemplateQuestionCondition_SingleChoice", "([TriggerType] <> 1) OR ([SelectedQuestionOptionId] IS NOT NULL AND [TriggerValue] IS NULL)");
                        });
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.Branch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameAr")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Branch");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.Department", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameAr")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Department");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.OperatorTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("OperatorId", "TemplateId")
                        .IsUnique();

                    b.ToTable("OperatorTemplate");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.Question", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Scope")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("TextAr")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("TextEn")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("GroupId");

                    b.HasIndex("Scope");

                    b.HasIndex("BranchId", "IsActive");

                    b.HasIndex("Scope", "IsActive");

                    b.ToTable("Question", null, t =>
                        {
                            t.HasCheckConstraint("CK_Question_Scope_BranchId", "([Scope] = 1 AND [BranchId] IS NOT NULL) OR ([Scope] = 2 AND [BranchId] IS NULL)");
                        });
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.QuestionGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameAr")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Scope")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.HasIndex("NameEn")
                        .IsUnique()
                        .HasDatabaseName("UX_QuestionGroup_Global_NameEn")
                        .HasFilter("[Scope] = 2 AND [BranchId] IS NULL");

                    b.HasIndex("BranchId", "IsActive");

                    b.HasIndex("BranchId", "NameEn")
                        .IsUnique()
                        .HasDatabaseName("UX_QuestionGroup_Branch_NameEn")
                        .HasFilter("[Scope] = 1 AND [BranchId] IS NOT NULL");

                    b.HasIndex("Scope", "IsActive");

                    b.ToTable("QuestionGroup", null, t =>
                        {
                            t.HasCheckConstraint("CK_QuestionGroup_Scope_BranchId", "([Scope] = 1 AND [BranchId] IS NOT NULL) OR ([Scope] = 2 AND [BranchId] IS NULL)");
                        });
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.QuestionOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TextAr")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("TextEn")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("Value")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuestionId", "Order")
                        .IsUnique();

                    b.ToTable("QuestionOption");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.SurveyAnswer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("QuestionType")
                        .HasColumnType("int");

                    b.Property<Guid?>("SelectedQuestionOptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("SmileValue")
                        .HasColumnType("int");

                    b.Property<int?>("StarRatingValue")
                        .HasColumnType("int");

                    b.Property<Guid>("SurveyResponseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TextAnswer")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("VoiceFileName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("SelectedQuestionOptionId");

                    b.HasIndex("SurveyResponseId", "QuestionId")
                        .IsUnique();

                    b.ToTable("SurveyAnswer");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.SurveyResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ActualScore")
                        .HasColumnType("int");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxScore")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("OperatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("ScorePercentage")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<DateTime>("SubmittedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.HasIndex("SubmittedOnUtc");

                    b.HasIndex("TemplateId");

                    b.HasIndex("TemplateId", "SubmittedOnUtc");

                    b.HasIndex("OperatorId", "TemplateId", "SubmittedOnUtc");

                    b.ToTable("SurveyResponse");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.SurveyResponseCustomInputValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IntegerValue")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StringValue")
                        .HasMaxLength(3000)
                        .HasColumnType("nvarchar(3000)");

                    b.Property<Guid>("SurveyResponseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TemplateCustomInputId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TypeSnapshot")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SurveyResponseId");

                    b.HasIndex("TemplateCustomInputId");

                    b.HasIndex("SurveyResponseId", "TemplateCustomInputId")
                        .IsUnique();

                    b.ToTable("SurveyResponseCustomInputValue", null, t =>
                        {
                            t.HasCheckConstraint("CK_SRCIV_Integer_Value", "([TypeSnapshot] <> 2) OR ([IntegerValue] IS NOT NULL AND [StringValue] IS NULL)");

                            t.HasCheckConstraint("CK_SRCIV_String_Value", "([TypeSnapshot] <> 1) OR ([StringValue] IS NOT NULL AND [IntegerValue] IS NULL)");
                        });
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ActiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ExpireTo")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameAr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BranchId");

                    b.ToTable("Template");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.TemplateCustomInput", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("LabelAr")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("LabelEn")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("int");

                    b.Property<int?>("MaxValue")
                        .HasColumnType("int");

                    b.Property<int?>("MinLength")
                        .HasColumnType("int");

                    b.Property<int?>("MinValue")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByApplicationUserId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("TemplateId", "Name")
                        .IsUnique();

                    b.HasIndex("TemplateId", "IsActive", "Order");

                    b.ToTable("TemplateCustomInput", null, t =>
                        {
                            t.HasCheckConstraint("CK_TemplateCustomInput_Integer_Validation", "([Type] <> 2) OR ([MinLength] IS NULL AND [MaxLength] IS NULL)");

                            t.HasCheckConstraint("CK_TemplateCustomInput_Length_Range", "([MinLength] IS NULL OR [MaxLength] IS NULL OR [MaxLength] >= [MinLength])");

                            t.HasCheckConstraint("CK_TemplateCustomInput_Order_Positive", "[Order] > 0");

                            t.HasCheckConstraint("CK_TemplateCustomInput_String_Validation", "([Type] <> 1) OR ([MinValue] IS NULL AND [MaxValue] IS NULL)");

                            t.HasCheckConstraint("CK_TemplateCustomInput_Value_Range", "([MinValue] IS NULL OR [MaxValue] IS NULL OR [MaxValue] >= [MinValue])");
                        });
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.TemplateQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("TemplateId", "QuestionId")
                        .IsUnique();

                    b.ToTable("TemplateQuestion");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.TemplateQuestionCondition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ChildTemplateQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<Guid>("ParentTemplateQuestionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SelectedQuestionOptionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TriggerType")
                        .HasColumnType("int");

                    b.Property<int?>("TriggerValue")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChildTemplateQuestionId");

                    b.HasIndex("ParentTemplateQuestionId");

                    b.HasIndex("SelectedQuestionOptionId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("TemplateId", "ChildTemplateQuestionId");

                    b.HasIndex("TemplateId", "ParentTemplateQuestionId");

                    b.HasIndex("TemplateId", "ParentTemplateQuestionId", "ChildTemplateQuestionId", "TriggerType", "SelectedQuestionOptionId")
                        .IsUnique()
                        .HasDatabaseName("UX_TQC_SingleChoice")
                        .HasFilter("[TriggerType] = 1 AND [SelectedQuestionOptionId] IS NOT NULL AND [TriggerValue] IS NULL AND [IsActive] = 1");

                    b.HasIndex("TemplateId", "ParentTemplateQuestionId", "ChildTemplateQuestionId", "TriggerType", "TriggerValue")
                        .IsUnique()
                        .HasDatabaseName("UX_TQC_ValueTrigger")
                        .HasFilter("[TriggerType] IN (2, 3) AND [SelectedQuestionOptionId] IS NULL AND [TriggerValue] IS NOT NULL AND [IsActive] = 1");

                    b.ToTable("TemplateQuestionCondition");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("NameAr")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameEn")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("ApplicationUser");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Identity.BranchAdmin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.HasIndex("BranchId");

                    b.ToTable("BranchAdmin");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Identity.BranchUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BranchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.HasIndex("BranchId");

                    b.ToTable("BranchUser");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Identity.DepartmentAdmin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.ToTable("DepartmentAdmin");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Identity.Operator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DepartmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.HasIndex("DepartmentId");

                    b.ToTable("Operator");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Identity.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSystemPermission")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Identity.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Role");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Identity.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique();

                    b.ToTable("RolePermission");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Identity.SuperAdmin", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId")
                        .IsUnique();

                    b.ToTable("SuperAdmin");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Identity.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CreatedByApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedOnUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("RoleId");

                    b.HasIndex("ApplicationUserId", "RoleId")
                        .IsUnique();

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.AnonymousSurveyAnswer", b =>
                {
                    b.HasOne("CustomerSurvey.Domain.Entities.AnonymousSurveyResponse", "AnonymousSurveyResponse")
                        .WithMany("Answers")
                        .HasForeignKey("AnonymousSurveyResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CustomerSurvey.Domain.Entities.AnonymousTemplateQuestion", "AnonymousTemplateQuestion")
                        .WithMany()
                        .HasForeignKey("AnonymousTemplateQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustomerSurvey.Domain.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustomerSurvey.Domain.Entities.QuestionOption", "SelectedQuestionOption")
                        .WithMany()
                        .HasForeignKey("SelectedQuestionOptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AnonymousSurveyResponse");

                    b.Navigation("AnonymousTemplateQuestion");

                    b.Navigation("Question");

                    b.Navigation("SelectedQuestionOption");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.AnonymousSurveyResponse", b =>
                {
                    b.HasOne("CustomerSurvey.Domain.Entities.AnonymousTemplate", "AnonymousTemplate")
                        .WithMany()
                        .HasForeignKey("AnonymousTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnonymousTemplate");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.AnonymousSurveyResponseCustomInputValue", b =>
                {
                    b.HasOne("CustomerSurvey.Domain.Entities.AnonymousSurveyResponse", "AnonymousSurveyResponse")
                        .WithMany("CustomInputValues")
                        .HasForeignKey("AnonymousSurveyResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CustomerSurvey.Domain.Entities.AnonymousTemplateCustomInput", "AnonymousTemplateCustomInput")
                        .WithMany()
                        .HasForeignKey("AnonymousTemplateCustomInputId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnonymousSurveyResponse");

                    b.Navigation("AnonymousTemplateCustomInput");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.AnonymousTemplate", b =>
                {
                    b.HasOne("CustomerSurvey.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.AnonymousTemplateCustomInput", b =>
                {
                    b.HasOne("CustomerSurvey.Domain.Entities.AnonymousTemplate", "AnonymousTemplate")
                        .WithMany("CustomInputs")
                        .HasForeignKey("AnonymousTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnonymousTemplate");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.AnonymousTemplateQuestion", b =>
                {
                    b.HasOne("CustomerSurvey.Domain.Entities.AnonymousTemplate", "AnonymousTemplate")
                        .WithMany("Questions")
                        .HasForeignKey("AnonymousTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustomerSurvey.Domain.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AnonymousTemplate");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.AnonymousTemplateQuestionCondition", b =>
                {
                    b.HasOne("CustomerSurvey.Domain.Entities.AnonymousTemplate", "AnonymousTemplate")
                        .WithMany()
                        .HasForeignKey("AnonymousTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustomerSurvey.Domain.Entities.AnonymousTemplateQuestion", "ChildAnonymousTemplateQuestion")
                        .WithMany()
                        .HasForeignKey("ChildAnonymousTemplateQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustomerSurvey.Domain.Entities.AnonymousTemplateQuestion", "ParentAnonymousTemplateQuestion")
                        .WithMany()
                        .HasForeignKey("ParentAnonymousTemplateQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustomerSurvey.Domain.Entities.QuestionOption", "SelectedQuestionOption")
                        .WithMany()
                        .HasForeignKey("SelectedQuestionOptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("AnonymousTemplate");

                    b.Navigation("ChildAnonymousTemplateQuestion");

                    b.Navigation("ParentAnonymousTemplateQuestion");

                    b.Navigation("SelectedQuestionOption");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.OperatorTemplate", b =>
                {
                    b.HasOne("CustomerSurvey.Domain.Identity.Operator", "Operator")
                        .WithMany("OperatorTemplates")
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustomerSurvey.Domain.Entities.Template", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Operator");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.Question", b =>
                {
                    b.HasOne("CustomerSurvey.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CustomerSurvey.Domain.Entities.QuestionGroup", "Group")
                        .WithMany("Questions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.QuestionGroup", b =>
                {
                    b.HasOne("CustomerSurvey.Domain.Entities.Branch", "Branch")
                        .WithMany("Groups")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.QuestionOption", b =>
                {
                    b.HasOne("CustomerSurvey.Domain.Entities.Question", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.SurveyAnswer", b =>
                {
                    b.HasOne("CustomerSurvey.Domain.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustomerSurvey.Domain.Entities.QuestionOption", "SelectedQuestionOption")
                        .WithMany()
                        .HasForeignKey("SelectedQuestionOptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CustomerSurvey.Domain.Entities.SurveyResponse", "SurveyResponse")
                        .WithMany("Answers")
                        .HasForeignKey("SurveyResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("SelectedQuestionOption");

                    b.Navigation("SurveyResponse");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.SurveyResponse", b =>
                {
                    b.HasOne("CustomerSurvey.Domain.Identity.Operator", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustomerSurvey.Domain.Entities.Template", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Operator");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.SurveyResponseCustomInputValue", b =>
                {
                    b.HasOne("CustomerSurvey.Domain.Entities.SurveyResponse", "SurveyResponse")
                        .WithMany("CustomInputValues")
                        .HasForeignKey("SurveyResponseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CustomerSurvey.Domain.Entities.TemplateCustomInput", "TemplateCustomInput")
                        .WithMany()
                        .HasForeignKey("TemplateCustomInputId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SurveyResponse");

                    b.Navigation("TemplateCustomInput");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.Template", b =>
                {
                    b.HasOne("CustomerSurvey.Domain.Entities.Branch", "Branch")
                        .WithMany("Templates")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.TemplateCustomInput", b =>
                {
                    b.HasOne("CustomerSurvey.Domain.Entities.Template", "Template")
                        .WithMany("CustomInputs")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.TemplateQuestion", b =>
                {
                    b.HasOne("CustomerSurvey.Domain.Entities.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustomerSurvey.Domain.Entities.Template", "Template")
                        .WithMany("TemplateQuestions")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.TemplateQuestionCondition", b =>
                {
                    b.HasOne("CustomerSurvey.Domain.Entities.TemplateQuestion", "ChildTemplateQuestion")
                        .WithMany()
                        .HasForeignKey("ChildTemplateQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustomerSurvey.Domain.Entities.TemplateQuestion", "ParentTemplateQuestion")
                        .WithMany()
                        .HasForeignKey("ParentTemplateQuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustomerSurvey.Domain.Entities.QuestionOption", "SelectedQuestionOption")
                        .WithMany()
                        .HasForeignKey("SelectedQuestionOptionId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("CustomerSurvey.Domain.Entities.Template", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ChildTemplateQuestion");

                    b.Navigation("ParentTemplateQuestion");

                    b.Navigation("SelectedQuestionOption");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Identity.BranchAdmin", b =>
                {
                    b.HasOne("CustomerSurvey.Domain.Identity.ApplicationUser", "ApplicationUser")
                        .WithOne()
                        .HasForeignKey("CustomerSurvey.Domain.Identity.BranchAdmin", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustomerSurvey.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Identity.BranchUser", b =>
                {
                    b.HasOne("CustomerSurvey.Domain.Identity.ApplicationUser", "ApplicationUser")
                        .WithOne()
                        .HasForeignKey("CustomerSurvey.Domain.Identity.BranchUser", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustomerSurvey.Domain.Entities.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Identity.DepartmentAdmin", b =>
                {
                    b.HasOne("CustomerSurvey.Domain.Identity.ApplicationUser", "ApplicationUser")
                        .WithOne()
                        .HasForeignKey("CustomerSurvey.Domain.Identity.DepartmentAdmin", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustomerSurvey.Domain.Entities.Department", "Department")
                        .WithMany("DepartmentAdmins")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Identity.Operator", b =>
                {
                    b.HasOne("CustomerSurvey.Domain.Identity.ApplicationUser", "ApplicationUser")
                        .WithOne()
                        .HasForeignKey("CustomerSurvey.Domain.Identity.Operator", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustomerSurvey.Domain.Entities.Department", "Department")
                        .WithMany("Operators")
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Department");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Identity.RolePermission", b =>
                {
                    b.HasOne("CustomerSurvey.Domain.Identity.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustomerSurvey.Domain.Identity.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Identity.SuperAdmin", b =>
                {
                    b.HasOne("CustomerSurvey.Domain.Identity.ApplicationUser", "ApplicationUser")
                        .WithOne()
                        .HasForeignKey("CustomerSurvey.Domain.Identity.SuperAdmin", "ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Identity.UserRole", b =>
                {
                    b.HasOne("CustomerSurvey.Domain.Identity.ApplicationUser", "ApplicationUser")
                        .WithMany("UserRoles")
                        .HasForeignKey("ApplicationUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CustomerSurvey.Domain.Identity.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApplicationUser");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.AnonymousSurveyResponse", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("CustomInputValues");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.AnonymousTemplate", b =>
                {
                    b.Navigation("CustomInputs");

                    b.Navigation("Questions");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.Branch", b =>
                {
                    b.Navigation("Groups");

                    b.Navigation("Templates");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.Department", b =>
                {
                    b.Navigation("DepartmentAdmins");

                    b.Navigation("Operators");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.Question", b =>
                {
                    b.Navigation("Options");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.QuestionGroup", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.SurveyResponse", b =>
                {
                    b.Navigation("Answers");

                    b.Navigation("CustomInputValues");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Entities.Template", b =>
                {
                    b.Navigation("CustomInputs");

                    b.Navigation("TemplateQuestions");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Identity.ApplicationUser", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Identity.Operator", b =>
                {
                    b.Navigation("OperatorTemplates");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Identity.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("CustomerSurvey.Domain.Identity.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
